name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: nuget/setup-nuget@v2

      - uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: nuget restore NintendoMetadata.sln

      - name: Build
        run: msbuild NintendoMetadata.csproj -p:Configuration=Release

      - name: Package
        run: |
          pip install invoke pyyaml
          mkdir tmp
          curl -L -O https://github.com/JosefNemec/Playnite/releases/download/10.12/Playnite1012.zip
          unzip Playnite1012.zip -d tmp/playnite
          invoke pack --toolbox ./tmp/playnite/Toolbox.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/*.pext
            dist/*.zip
