name: Publish

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build
        run: |
          pip install invoke pyyaml
          dotnet build -c Release

      - name: Package
        run: |
          mkdir tmp
          curl -L -O https://github.com/JosefNemec/Playnite/releases/download/10.12/Playnite1012.zip
          unzip Playnite1012.zip -d tmp/playnite
          invoke pack --toolbox ./tmp/playnite/Toolbox.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/*.pext
            dist/*.zip
